DROP TABLE IF EXISTS
compilation_event,compilations, requests, events, users, locations, categories;
CREATE TABLE IF NOT EXISTS categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) UNIQUE,
CONSTRAINT pk_categories PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS locations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
lon DOUBLE PRECISION NOT NULL,
lat DOUBLE PRECISION NOT NULL,
CONSTRAINT pk_locations PRIMARY KEY (id),
UNIQUE (lon, lat)
);
CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL UNIQUE,
CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS events (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
annotation VARCHAR(2000) NOT NULL,
category_id BIGINT,
confirmed_requests INT,
created_on TIMESTAMP WITH TIME ZONE NOT NULL,
description VARCHAR(7000) NOT NULL,
event_date TIMESTAMP WITH TIME ZONE NOT NULL,
initiator_id BIGINT NOT NULL,
location_id BIGINT NOT NULL,
is_paid BOOLEAN NOT NULL,
participant_limit BIGINT,
published_on TIMESTAMP WITH TIME ZONE,
request_moderation BOOLEAN NOT NULL,
state VARCHAR(255) NOT NULL,
title VARCHAR(255) NOT NULL,
views BIGINT,
CONSTRAINT pk_events PRIMARY KEY (id),
CONSTRAINT fk_event_user FOREIGN KEY (initiator_id) REFERENCES users (id),
CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES locations (id),
CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id)
);
CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
event_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
status VARCHAR(255) NOT NULL,
created TIMESTAMP WITH TIME ZONE NOT NULL,
CONSTRAINT pk_requests PRIMARY KEY (id),
CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events (id),
CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users (id),
UNIQUE (event_id, user_id)
);
CREATE TABLE IF NOT EXISTS compilations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY,
compilation_id BIGINT,
pinned BOOLEAN NOT NULL,
title VARCHAR(50) NOT NULL UNIQUE,
CONSTRAINT pk_compilations PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS compilation_event (
compilation_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
CONSTRAINT fk_ce_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id),
CONSTRAINT fk_ce_event FOREIGN KEY (event_id) REFERENCES events (id)
);


